Agcol - verify and timeout
CatusKing/Ideologies-Network pull request #1
Opened 2024-04-12 23:51 UTC by AGCol11

2024-04-13 15:02 UTC, CatusKing commented
You need to list the commands you worked on.

2024-04-13 15:35 UTC, CatusKing commented
### Kick and Ban
- Needs to log in a log channel
- Response to reply can be short like "Banned CatusKing"
- Commands should only be visible to people with ban perms. This means changing the slash command builder so it shows only to people with certain perms. This is rather then checking perms.
- the kick function for the member object calls for a string as a reason not an object
### Timeout
- remove embeds but keep formatt
- remove timeout delete button
- we should probably add a cancel timeout feature
### Verify
- doesnt make sure file type is an image
- also should use both tag and ping to show who used it

2024-04-16 17:52 UTC, AGCol11 commented
fixed all noted

2024-04-16 23:19 UTC, CatusKing requested changes
Just some simple things. Also sorry for updating your code with the verify. Realized I could use this feature instead.

2024-04-16 23:19 UTC, CatusKing commented on src/commands/Moderation/ban.js
> +        const reason = interaction.options.getString('reason') || 'No reason provided';
If the command option is required you dont need an or for the definition

2024-04-16 23:19 UTC, CatusKing commented on src/commands/Moderation/kick.js
> +        const reason = interaction.options.getString('reason') || 'No reason provided';
If the command option is required you dont need an or for the definition

2024-04-16 23:19 UTC, CatusKing commented on src/commands/Moderation/timeout.js
> +        .addStringOption(option => option.setName('reason').setDescription('Reason for timing out the user')),
Please require and update code accordingly.

2024-04-16 23:19 UTC, CatusKing commented on src/commands/Moderation/verify.js
> +                        if (msg.attachments.size > 0 && msg.attachments.every(attachment => attachment.contentType.startsWith('image'))) {
Could you check the send to check if they are the interaction user.

2024-04-30 22:40 UTC, CatusKing commented on src/commands/Moderation/verify.js
> +                        if (msg.attachments.size > 0 && msg.attachments.every(attachment => attachment.contentType.startsWith('image'))) {
Phrased that horribly. When it recieves the callback you should confirm it's from the original sender.

2024-04-30 22:46 UTC, CatusKing requested changes
Additional reminder on permission checking.

2024-04-30 22:46 UTC, CatusKing commented on src/commands/Moderation/timeout.js
> +        if(!interaction.member.permissions.has(PermissionsBitField.Flags.ModerateMembers)) return await interaction.reply({ content: 'You do not have permission to use this command', ephemeral: true}
Remember we have default permissions we can change in the command creation.

2024-05-23 00:19 UTC, merged